pokedex = [
    {'nombre': 'Bulbasaur', 'numero': 1, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': False, 'gigamax': False},
    {'nombre': 'Ivysaur', 'numero': 2, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': False, 'gigamax': False},
    {'nombre': 'Venusaur', 'numero': 3, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': True, 'gigamax': False},
    {'nombre': 'Charmander', 'numero': 4, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Charmeleon', 'numero': 5, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Charizard', 'numero': 6, 'tipos': ['Fire', 'Flying'], 'debilidades': ['Water', 'Electric', 'Rock'], 'mega': True, 'gigamax': True},
    {'nombre': 'Squirtle', 'numero': 7, 'tipos': ['Water'], 'debilidades': ['Electric', 'Grass'], 'mega': False, 'gigamax': False},
    {'nombre': 'Wartortle', 'numero': 8, 'tipos': ['Water'], 'debilidades': ['Electric', 'Grass'], 'mega': False, 'gigamax': False},
    {'nombre': 'Blastoise', 'numero': 9, 'tipos': ['Water'], 'debilidades': ['Electric', 'Grass'], 'mega': True, 'gigamax': False},
    {'nombre': 'Pikachu', 'numero': 25, 'tipos': ['Electric'], 'debilidades': ['Ground'], 'mega': False, 'gigamax': False},
    {'nombre': 'Raichu', 'numero': 26, 'tipos': ['Electric'], 'debilidades': ['Ground'], 'mega': False, 'gigamax': False},
    {'nombre': 'Jolteon', 'numero': 135, 'tipos': ['Electric'], 'debilidades': ['Ground'], 'mega': False, 'gigamax': False},
    {'nombre': 'Sandshrew', 'numero': 27, 'tipos': ['Ground'], 'debilidades': ['Water', 'Grass', 'Ice'], 'mega': False, 'gigamax': False},
    {'nombre': 'Clefairy', 'numero': 35, 'tipos': ['Fairy'], 'debilidades': ['Poison', 'Steel'], 'mega': False, 'gigamax': False},
    {'nombre': 'Vulpix', 'numero': 37, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Ninetales', 'numero': 38, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Jigglypuff', 'numero': 39, 'tipos': ['Normal', 'Fairy'], 'debilidades': ['Poison', 'Steel'], 'mega': False, 'gigamax': False},
    {'nombre': 'Zubat', 'numero': 41, 'tipos': ['Poison', 'Flying'], 'debilidades': ['Electric', 'Ice', 'Psychic', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Oddish', 'numero': 43, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': False, 'gigamax': False},
    {'nombre': 'Gloom', 'numero': 44, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': False, 'gigamax': False},
    {'nombre': 'Vileplume', 'numero': 45, 'tipos': ['Grass', 'Poison'], 'debilidades': ['Fire', 'Psychic', 'Flying'], 'mega': False, 'gigamax': False},
    {'nombre': 'Machop', 'numero': 66, 'tipos': ['Fighting'], 'debilidades': ['Flying', 'Psychic', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Machoke', 'numero': 67, 'tipos': ['Fighting'], 'debilidades': ['Flying', 'Psychic', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Machamp', 'numero': 68, 'tipos': ['Fighting'], 'debilidades': ['Flying', 'Psychic', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Geodude', 'numero': 74, 'tipos': ['Rock', 'Ground'], 'debilidades': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel', 'Ice'], 'mega': False, 'gigamax': False},
    {'nombre': 'Golem', 'numero': 76, 'tipos': ['Rock', 'Ground'], 'debilidades': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel', 'Ice'], 'mega': False, 'gigamax': False},
    {'nombre': 'Ponyta', 'numero': 77, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Rapidash', 'numero': 78, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Gastly', 'numero': 92, 'tipos': ['Ghost', 'Poison'], 'debilidades': ['Ground', 'Psychic', 'Ghost', 'Dark'], 'mega': False, 'gigamax': False},
    {'nombre': 'Haunter', 'numero': 93, 'tipos': ['Ghost', 'Poison'], 'debilidades': ['Ground', 'Psychic', 'Ghost', 'Dark'], 'mega': False, 'gigamax': False},
    {'nombre': 'Gengar', 'numero': 94, 'tipos': ['Ghost', 'Poison'], 'debilidades': ['Ground', 'Psychic', 'Ghost', 'Dark'], 'mega': False, 'gigamax': False},
    {'nombre': 'Onix', 'numero': 95, 'tipos': ['Rock', 'Ground'], 'debilidades': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel', 'Ice'], 'mega': False, 'gigamax': False},
    {'nombre': 'Scyther', 'numero': 123, 'tipos': ['Bug', 'Flying'], 'debilidades': ['Fire', 'Electric', 'Ice', 'Flying', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Electabuzz', 'numero': 125, 'tipos': ['Electric'], 'debilidades': ['Ground'], 'mega': False, 'gigamax': False},
    {'nombre': 'Magmar', 'numero': 126, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Pinsir', 'numero': 127, 'tipos': ['Bug'], 'debilidades': ['Fire', 'Flying', 'Rock'], 'mega': True, 'gigamax': False},
    {'nombre': 'Tauros', 'numero': 128, 'tipos': ['Normal'], 'debilidades': ['Fighting'], 'mega': False, 'gigamax': False},
    {'nombre': 'Magikarp', 'numero': 129, 'tipos': ['Water'], 'debilidades': ['Electric', 'Grass'], 'mega': False, 'gigamax': False},
    {'nombre': 'Gyarados', 'numero': 130, 'tipos': ['Water', 'Flying'], 'debilidades': ['Electric', 'Rock'], 'mega': True, 'gigamax': False},
    {'nombre': 'Lapras', 'numero': 131, 'tipos': ['Water', 'Ice'], 'debilidades': ['Electric', 'Grass', 'Fighting', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Eevee', 'numero': 133, 'tipos': ['Normal'], 'debilidades': ['Fighting'], 'mega': False, 'gigamax': False},
    {'nombre': 'Vaporeon', 'numero': 134, 'tipos': ['Water'], 'debilidades': ['Electric', 'Grass'], 'mega': False, 'gigamax': False},
    {'nombre': 'Flareon', 'numero': 136, 'tipos': ['Fire'], 'debilidades': ['Water', 'Ground', 'Rock'], 'mega': False, 'gigamax': False},
    {'nombre': 'Espeon', 'numero': 196, 'tipos': ['Psychic'], 'debilidades': ['Bug', 'Ghost', 'Dark'], 'mega': False, 'gigamax': False},
    {'nombre': 'Umbreon', 'numero': 197, 'tipos': ['Dark'], 'debilidades': ['Fighting', 'Bug', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Bagon', 'numero': 371, 'tipos': ['Dragon'], 'debilidades': ['Ice', 'Dragon', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Shelgon', 'numero': 372, 'tipos': ['Dragon'], 'debilidades': ['Ice', 'Dragon', 'Fairy'], 'mega': False, 'gigamax': False},
    {'nombre': 'Salamence', 'numero': 373, 'tipos': ['Dragon', 'Flying'], 'debilidades': ['Ice', 'Dragon', 'Rock', 'Fairy'], 'mega': True, 'gigamax': False},
    {'nombre': 'Tyrantrum', 'numero': 697, 'tipos': ['Rock', 'Dragon'], 'debilidades': ['Ground', 'Fighting', 'Steel', 'Water', 'Dragon'], 'mega': False, 'gigamax': False},
    {'nombre': 'Lycanroc', 'numero': 745, 'tipos': ['Rock'], 'debilidades': ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'], 'mega': False, 'gigamax': False},
]
